services:
  backend:
    build:
      context: ./web
      dockerfile: Dockerfile-deploy
    ports:
      - "3000:3000"
    volumes:
      # Specify the path to use as the root of the storage before the colon (:).
      - /mnt:/storage