# docker-compose for development environment
services:
  frontend:
    build: ./web/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./web/frontend:/app
      - /app/node_modules
  backend:
    command: npm run dev
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web/backend:/app
      - /app/node_modules
      - /app/dist
      
      # Specify the path to use as the root before the colon(:).
      - /mnt/zdev:/storage
